services:
  python:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:8888"
    volumes:
      # mount current repo to a Docker folder under the home user directory (default is rstudio)
      # refer to repo files with relative path
      - ./app:/app
      # mount Biopharma_Shared_Workspace on SharePoint HAI to a Docker folder under root directory
      # make sure you have access to the shared workspace if using OneDrive
      # make sure you have no spaces in your path (if you do, create a symbolic link.)
      - ./shared:/shared
    working_dir: /app
    environment:
      # disable authentication
      - DISABLE_AUTH=true
      # pass database (DSCA PHI) credential as environment variables
      - PGHOST=host.docker.internal
      - PGPORT=${PGPORT}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
    container_name: "biopharma_jupyter"